task/urls.py
from django.urls import path

from task.views import TaskListView, TagListView, TagUpdateView, TagDeleteView, TaskUpdateView, TaskDeleteView, \
    task_complete_view

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("tags/", TagListView.as_view(), name="tag"),
    path("tags/update/<int:pk>", TagUpdateView.as_view(), name="tag-update"),
    path("tags/delete/<int:pk>", TagDeleteView.as_view(), name="tag-delete"),
    path("tasks/update/<int:pk>", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/delete/<int:pk>", TaskDeleteView.as_view(), name="task-delete"),
    path("tasks/complite/<int:pk>", task_complete_view, name="task-complete"),
]


app_name = "task"

task_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("task.urls", namespace="task")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.name}"


class Task(models.Model):
    content = models.CharField(max_length=255)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, default=None)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["is_done", "datetime"]

task/forms.py
from django import forms


from task.models import Task, Tag


class TaskTagUpdateForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Task
        fields = "__all__"

task/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from task.forms import TaskTagUpdateForm
from task.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task


class TagListView(generic.ListView):
    model = Tag


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task:tag")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("task:tag")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskTagUpdateForm
    success_url = reverse_lazy("task:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task:index")


def task_complete_view(request, pk):
    task = Task.objects.get(id=pk)
    if task.is_done:
        task.is_done = False
    else:
        task.is_done = True
    task.save()
    return HttpResponseRedirect(reverse_lazy("task:index"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Taxi Service</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row row_class">
        <div class="sidebar_ col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="content_ col-sm-10">

            {% block content %}{% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'task:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'task:tag' %}">Tags</a></li>
</ul>

templates/task/tag_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <form action="" method="post">
    <p>Are you sure you want to delete this tag?</p>
    <button class="btn-danger">Confirm</button>
  </form>
{%  endblock %}

templates/task/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn-success">Update</button>
  </form>
{% endblock %}

templates/task/tag_list.html
{% extends "base.html" %}
{% block content %}
  <table class="table">
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
    {% for tag in tag_list %}
      <tr>
        <td>{{ tag.id }}</td>
        <td>{{ tag.name }}</td>
        <td>
          <a href="{% url 'task:tag-update' pk=tag.id %}" class="btn btn-dark">Update</a>
        </td>
        <td>
          <a href="{% url 'task:tag-delete' pk=tag.id %}" class="btn btn-dark">Delete</a>
        </td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

templates/task/task_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <form action="" method="post">
    <p>Are you sure you want to delete this task?</p>
    <button class="btn-danger">Confirm</button>
  </form>
{%  endblock %}

templates/task/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
  <button type="submit" class="btn-success">Update</button>
  </form>
{% endblock %}

templates/task/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>TODO list</h1>
  {% for task in task_list %}
    <p>
      <strong>
        {{ task.content }}
        {% if task.is_done %}
          <span class="text-success">Done</span>
        {% else %}
          <span class="text-danger">Not done</span>
        {% endif %}
      </strong>
    </p>
    {%  if task.is_done %}
      <a href="{% url 'task:task-complete' pk=task.id %}" class="btn btn-dark link-to-page">Undo</a>
    {% else %}
      <a href="{% url 'task:task-complete' pk=task.id %}" class="btn btn-success link-to-page">Compete</a>
    {% endif %}
    <p>
      Created: {{ task.datetime }}
      {% if task.deadline %}
        Deadline: {{ task.deadline }}
      {% endif %}
    </p>
    <p>
      Tags:
      {% for tag in task.tags.all %}
        {{ tag.name }}
      {% endfor %}
      <a href="{% url 'task:task-update' pk=task.id %}" class="btn btn-link">Update</a>
      <a href="{% url 'task:task-delete' pk=task.id %}" class="btn btn-link">Delete</a>
    </p>
    <hr>
  {% endfor %}
{% endblock %}